
services:
  # FastAPI Application
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: donnhasach-api
    ports:
      - "${API_PORT:-8888}:8888"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/__pycache__
    restart: unless-stopped
    command: >
      sh -c "
        echo 'Starting FastAPI application...' &&
        echo 'Connecting to external database and Redis...' &&
        uvicorn app.main:app --host 0.0.0.0 --port 8888 --reload
      "
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s 