"""add policy type

Revision ID: 3364a335b360
Revises: c7dd24eca7b8
Create Date: 2025-02-20 08:11:44.667950+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3364a335b360'
down_revision = 'c7dd24eca7b8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images', 'json_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.add_column('sessions', sa.Column('policy_type', sa.String(length=100), nullable=True))
    op.alter_column('sessions', 'id_keycloak',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sessions', 'id_keycloak',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('sessions', 'policy_type')
    op.alter_column('images', 'json_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    # ### end Alembic commands ### 