"""init db

Revision ID: 83abfacd7acc
Revises: 
Create Date: 2025-02-25 10:10:43.706831+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '83abfacd7acc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('analysis_id', sa.String(), nullable=False),
    sa.Column('assessment_id', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('scan_image_url', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'SUCCESS', 'FAILED', name='claimimagestatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('json_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('keycloak_user_id', sa.String(), nullable=True),
    sa.Column('device_token', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('analysis_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    # ### end Alembic commands ### 