"""add device token and folder_id

Revision ID: 05c35f6cc18a
Revises: b2f6a51e0e6e
Create Date: 2025-02-25 08:38:40.494547+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05c35f6cc18a'
down_revision = 'b2f6a51e0e6e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('device_token', sa.String(), nullable=True))
    op.add_column('images', sa.Column('folder_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'folder_id')
    op.drop_column('images', 'device_token')
    # ### end Alembic commands ### 