"""add keycloak id

Revision ID: d7b41416c4c5
Revises: 5742edc151f6
Create Date: 2025-02-19 11:15:17.683911+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7b41416c4c5'
down_revision = '5742edc151f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('id_keycloak', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'id_keycloak')
    # ### end Alembic commands ### 