"""add_responsible_id_to_sessions

Revision ID: bdd5891b3e92
Revises: 3364a335b360
Create Date: 2025-02-21 04:17:22.029973+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdd5891b3e92'
down_revision = '3364a335b360'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('responsible_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'responsible_id')
    # ### end Alembic commands ### 