"""add auto annalysis

Revision ID: 045ee516f619
Revises: 550395c05dbb
Create Date: 2025-02-27 04:51:22.332849+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '045ee516f619'
down_revision = '550395c05dbb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('auto_analysis', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'auto_analysis')
    # ### end Alembic commands ### 