"""add name in session

Revision ID: 9f16bc049b6f
Revises: 89e37b585202
Create Date: 2025-02-21 12:18:18.304324+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f16bc049b6f'
down_revision = '89e37b585202'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('responsible_name', sa.Text(), nullable=True))
    op.add_column('sessions', sa.Column('partner_channel_name', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'partner_channel_name')
    op.drop_column('sessions', 'responsible_name')
    # ### end Alembic commands ### 