"""add is_suspecting_wrongly to images

Revision ID: d59ac8262d0e
Revises: bdd5891b3e92
Create Date: 2025-02-21 06:36:16.929504+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd59ac8262d0e'
down_revision = 'bdd5891b3e92'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('is_suspecting_wrongly', sa.Boolean(), server_default='false', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'is_suspecting_wrongly')
    # ### end Alembic commands ### 