"""add image_id

Revision ID: 550395c05dbb
Revises: 16cc0f1ac4c0
Create Date: 2025-02-26 07:38:15.250831+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '550395c05dbb'
down_revision = '16cc0f1ac4c0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'id')
    # ### end Alembic commands ### 