"""add image_base64

Revision ID: 6739c7092d7c
Revises: 6c8b76fc82a7
Create Date: 2025-03-11 09:06:24.283233+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6739c7092d7c'
down_revision = '6c8b76fc82a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_repair_items_id', table_name='repair_items')
    op.drop_table('repair_items')
    op.add_column('images', sa.Column('image_base64', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'image_base64')
    op.create_table('repair_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('repair_item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('repair_item_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('category_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='repair_items_pkey'),
    sa.UniqueConstraint('category_id', 'repair_item_name', name='uq_category_repair_item')
    )
    op.create_index('ix_repair_items_id', 'repair_items', ['id'], unique=False)
    # ### end Alembic commands ### 