"""add field mutable list

Revision ID: 16cc0f1ac4c0
Revises: 18e73ccfad54
Create Date: 2025-02-26 07:01:19.255638+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '16cc0f1ac4c0'
down_revision = '18e73ccfad54'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('list_json_data', postgresql.ARRAY(postgresql.JSON(astext_type=sa.Text())), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'list_json_data')
    # ### end Alembic commands ### 