"""migration name

Revision ID: d66c2297616b
Revises: d59ac8262d0e
Create Date: 2025-02-21 11:21:22.045228+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd66c2297616b'
down_revision = 'd59ac8262d0e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('partner_channel_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'partner_channel_id')
    # ### end Alembic commands ### 