"""add_scan_image_url

Revision ID: 89e37b585202
Revises: d66c2297616b
Create Date: 2025-02-21 11:47:38.329621+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89e37b585202'
down_revision = 'd66c2297616b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('scan_image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'scan_image_url')
    # ### end Alembic commands ### 