"""add error_message to sessions

Revision ID: a8e6239511b4
Revises: 9f16bc049b6f
Create Date: 2025-02-24 03:24:03.464153+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8e6239511b4'
down_revision = '9f16bc049b6f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('error_message', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'error_message')
    # ### end Alembic commands ### 