targetPort: 5000 # port of pod container
ingress:
  enable: true
  host: dev-api-insurance.baohiemtasco.vn
  path: /acg-xm
#  annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: /$1
envFrom:
  configMaps:
    - name: common-cm
    - name: redis1-cm
    - name: keycloak-cm
resources:
  requests:
    cpu: "50m"
    memory: "200Mi"
  limits:
    cpu: "400m"
    memory: "1Gi"
celeries:
  - name: image_processor
    replicas: 1
    runCommand: python -m app.workers.image_processor
    resources:
      requests:
        cpu: 50m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi
  - name: policy_creator
    replicas: 1
    runCommand: python -m app.workers.policy_creator
    resources:
      requests:
        cpu: 50m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi 

depCommand: ./run.sh


