targetPort: 8000 # port of pod container
ingress:
  enable: true
  host: dev-api-insurance.baohiemtasco.vn
  path: /acg-xm

envFrom:
  configMaps:
    - name: xm-common-cm
    - name: keycloak-cm

resources:
  requests:
    cpu: "50m"
    memory: "200Mi"
  limits:
    cpu: "400m"
    memory: "1Gi"

celeries:
  - name: acg-xm-image-processor
    replicas: 1
    runCommand: python -m app.workers.image_processor
    resources:
      requests:
        cpu: 50m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi

  - name: acg-xm-policy-creator
    replicas: 1
    runCommand: python -m app.workers.policy_creator
    resources:
      requests:
        cpu: 50m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi 

# depCommand: ./run.sh

