targetPort: 8000 # port of pod container
ingress:
  enable: true
  host: api-insurance.baohiemtasco.vn
  path: /acg-xm(/|$)(.*)
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2


tls:
  - hosts:
      - '*.baohiemtasco.vn'
    secretName: baohiemtasco-vn-tls-sectigo-wildcard

envFrom:
  configMaps:
    - name: xm-common-cm
    - name: keycloak-cm

resources:
  requests:
    cpu: "50m"
    memory: "200Mi"
  limits:
    cpu: "400m"
    memory: "1Gi"

celeries:
  - name: acg-xm-image-processor
    replicas: 1
    runCommand: python -m app.workers.image_processor
    resources:
      requests:
        cpu: 50m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi

  - name: acg-xm-policy-creator
    replicas: 1
    runCommand: python -m app.workers.policy_creator
    resources:
      requests:
        cpu: 50m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi 

  # - name: acg-xm-session-processor
  #   replicas: 1
  #   runCommand: python -m app.workers.session_processor
  #   resources:
  #     requests: 
  #       cpu: 50m
  #       memory: 512Mi
  #     limits:
  #       cpu: 500m
  #       memory: 1Gi

# depCommand: ./run.sh

